#!/bin/bash
#the -echo option in the command disables the output to the terminal,whereas echo enables output
echo -e "Enter your password: "
stty -echo
read password
stty echo
echo
echo Password is $password


#second way: read password in the nonechoed mode using -s
read -s password

